CREATE TABLE IF NOT EXISTS raw_air_quality (
id SERIAL PRIMARY KEY,
city TEXT, country TEXT,
lat TEXT,
lon TEXT,
aqi TEXT,
dominentpol TEXT,
time_utc TEXT,
iaqi_pm25 TEXT,
iaqi_pm10 TEXT,
iaqi_o3 TEXT,
iaqi_no2 TEXT,
iaqi_so2 TEXT,
iaqi_co TEXT,
iaqi_t TEXT,
iaqi_h TEXT,
iaqi_w TEXT,
iaqi_p TEXT,
source_url TEXT,
attribution_names TEXT,
attribution_urls TEXT,
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP);


CREATE TABLE IF NOT EXISTS raw_air_forecast (
id SERIAL PRIMARY KEY,
city TEXT,
day TEXT,
pm25_avg TEXT,
pm25_min TEXT,
pm25_max TEXT,
pm10_avg TEXT,
pm10_min TEXT,
pm10_max TEXT,
o3_avg TEXT,
o3_min TEXT,
o3_max TEXT,
uvi_avg TEXT,
uvi_min TEXT,
uvi_max TEXT,
collected_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP); 

CREATE TABLE IF NOT EXISTS raw_weather_data (
id SERIAL PRIMARY KEY,
city TEXT,
country TEXT,
lat TEXT,
lon TEXT,
weather_main TEXT,
weather_description TEXT,
weather_icon TEXT,
temp TEXT,
feels_like TEXT,
temp_min TEXT,
temp_max TEXT,
pressure TEXT,
humidity TEXT,
sea_level TEXT,
ground_level TEXT,
visibility TEXT,
wind_speed TEXT,
wind_deg TEXT,
clouds TEXT,
sunrise TEXT,
sunset TEXT,
measured_at_utc TEXT,
collected_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP);
